package com.example.rps.security;

import com.example.rps.player.PlayerEntity;
import lombok.Value;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.util.Collection;
import java.util.List;

@Value
public class UserDetailsImpl implements UserDetails {

    PlayerEntity playerEntity;

    /**
     * Autogenerated methods from UserDetails interface
     * **/

    @Override  // returns a list of roles
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return List.of(new SimpleGrantedAuthority(playerEntity.getRole().name()));
    }

    @Override
    public String getPassword() {
        return playerEntity.getPassword();
    }

    @Override
    public String getUsername() {
        return playerEntity.getUsername();
    }

    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    public boolean isEnabled() {
        return true;
    }
}
